apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      serviceAccountName: my-app-dev
      containers:
        - name: my-app
          image: nginx:1.14.2
          ports:
            - name: http
              containerPort: 80
              protocol: TCP