apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: my-app-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      serviceAccountName: my-app-dev
      imagePullSecrets:
        - name: artifactory-pull-secret
      containers:
        - name: my-app
          image: earldata.jfrog.io/default-docker-virtual/my-app:0.1.0
          ports:
            - name: http
              containerPort: 80
              protocol: TCP